/* Generated By:JJTree: Do not edit this line. ASTiMonitorClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.io.PrintWriter;
import java.util.HashSet;

public
class ASTiMonitorClass extends SimpleNode {
	private HashSet<String> classFields;
	private String monitorName;
  public ASTiMonitorClass(int id) {
    super(id);
		classFields = new HashSet<String>();
		monitorName = "__monitor__" + System.currentTimeMillis() % 1000;
  }
// Manually inserted code begins here
	public void addClassField(Token t) {
		classFields.add(t.image);
	}
	public String getMonitorName() { return monitorName; }
  public void process (PrintWriter ostr) {
    Token t = begin; // t corresponds to the "{" of the special block.
    System.out.println("class begin: " + t.image);
    
    ASTiMonitorMethod bnode;
    for (int i = 0; i < jjtGetNumChildren(); i++) {

      bnode = (ASTiMonitorMethod)jjtGetChild(i);
      while (t != bnode.begin) {
				if(!t.image.equals("monitor")) {
					print(t, ostr);
				}
        t = t.next;
			}
     	
     	bnode.process(ostr);
      t = bnode.end.next;
    }
    
    while (t != end) {
    	if(!t.image.equals("monitor")) {
				print(t, ostr);
			}
      t = t.next;
    }
    // t now corresponds to the last "}" of the special block.
    print(t, ostr);
  }
}
/* JavaCC - OriginalChecksum=fd808cf5c2b043f2fce4a101f6c170de (do not edit this line) */
